
name: Schedule Google Colab

on:
  schedule:
    # Runs at 6:00 AM UTC daily
    - cron: '0 6 * * *'

jobs:
  run-colab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Python dependencies
      run: |
        pip install gdown jupyter

    - name: Download Colab Notebook
      run: |
        gdown https://drive.google.com/uc?id=1TkGWwwpJmdE3zu7d6avODaa_sMWgXLmj -O Your_Notebook_Name.ipynb

    - name: Execute Colab Notebook
      run: |
        jupyter nbconvert --to notebook --execute sayHelloColab.ipynb --output result.ipynb 
